services:
  api:
    image: ghcr.io/mathiaslopez/todo-devops-lab:latest
    ports:
      - "8000:8000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    command: sh -c "/wait-for-it.sh db:5432 --timeout=30 --strict -- uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
