services: 
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: "no"
    networks:
      - shared-network

  db:
    restart: "no"
    networks:
      - shared-network

networks:
  shared-network:
    external: true