"""add modified fields for audits

Revision ID: aaa20d645e83
Revises: 107638094223
Create Date: 2025-10-20 22:53:35.106104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaa20d645e83'
down_revision: Union[str, Sequence[str], None] = '107638094223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('boards', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.add_column('boards', sa.Column('modified_by', sa.UUID(), nullable=False))
    op.add_column('tasks', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.add_column('tasks', sa.Column('modified_by', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'modified_by')
    op.drop_column('tasks', 'modified_at')
    op.drop_column('boards', 'modified_by')
    op.drop_column('boards', 'modified_at')
    op.drop_column('boards', 'created_by')
    # ### end Alembic commands ###
