"""add board table

Revision ID: c19b90477340
Revises: a9a7154a60be
Create Date: 2025-10-19 15:25:32.317765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19b90477340'
down_revision: Union[str, Sequence[str], None] = 'a9a7154a60be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('board_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'board_id')
    op.drop_table('boards')
    # ### end Alembic commands ###
