"""roles_permissions

Revision ID: f7853127aa6d
Revises: 2a8a26c5bfa5
Create Date: 2026-03-04 00:54:41.774268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7853127aa6d'
down_revision: Union[str, Sequence[str], None] = '2a8a26c5bfa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.add_column('board_user_permissions', sa.Column('role_id', sa.UUID(), nullable=True))
    
    op.create_foreign_key(None, 'board_user_permissions', 'roles', ['role_id'], ['id'])

    system_user_id = "00000000-0000-0000-0000-000000000000"

    op.execute(f"""
        INSERT INTO permissions (id, name, description, created_at, created_by, modified_at, modified_by)
        VALUES
            ('7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid, 'board.view', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('1c4f1cdd-b4c5-41f4-b55d-2178356bd002'::uuid, 'board.update', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('d7c47de2-2c1d-4c8a-8bc2-0f5c9d81a003'::uuid, 'board.delete', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('5b6e8f3a-2a6c-447e-9c60-7c15f50d4004'::uuid, 'board.manage_members', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('9c8f7e61-5f3d-4b7f-bc65-0c6a7a9d8005'::uuid, 'task.create', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('0e6d3a8b-0c8f-4a19-a2a9-8d6a3c8d7006'::uuid, 'task.update', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('2e3a9c8d-7d6b-4f3e-9b1c-5a6d7c8e9007'::uuid, 'task.delete', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('4f7c6b2a-8d9e-4c1f-b0b7-6a8d5c2e1008'::uuid, 'tag.manage', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid)
        ON CONFLICT (id) DO NOTHING;
    """)

    op.execute(f"""
        INSERT INTO roles (id, name, description, created_at, created_by, modified_at, modified_by)
        VALUES
            ('00000000-0000-0000-0000-000000000001'::uuid, 'owner', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, 'admin', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000003'::uuid, 'member', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000004'::uuid, 'viewer', NULL, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid)
        ON CONFLICT (id) DO NOTHING;
    """)

    op.execute(f"""
        INSERT INTO role_permissions (role_id, permission_id, created_at, created_by, modified_at, modified_by)
        VALUES
            -- owner: all permissions
            ('00000000-0000-0000-0000-000000000001'::uuid, '7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '1c4f1cdd-b4c5-41f4-b55d-2178356bd002'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, 'd7c47de2-2c1d-4c8a-8bc2-0f5c9d81a003'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '5b6e8f3a-2a6c-447e-9c60-7c15f50d4004'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '9c8f7e61-5f3d-4b7f-bc65-0c6a7a9d8005'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '0e6d3a8b-0c8f-4a19-a2a9-8d6a3c8d7006'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '2e3a9c8d-7d6b-4f3e-9b1c-5a6d7c8e9007'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '4f7c6b2a-8d9e-4c1f-b0b7-6a8d5c2e1008'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            -- admin: all except board.delete
            ('00000000-0000-0000-0000-000000000002'::uuid, '7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '1c4f1cdd-b4c5-41f4-b55d-2178356bd002'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '5b6e8f3a-2a6c-447e-9c60-7c15f50d4004'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '9c8f7e61-5f3d-4b7f-bc65-0c6a7a9d8005'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '0e6d3a8b-0c8f-4a19-a2a9-8d6a3c8d7006'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '2e3a9c8d-7d6b-4f3e-9b1c-5a6d7c8e9007'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '4f7c6b2a-8d9e-4c1f-b0b7-6a8d5c2e1008'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            -- member: board.view, task.create, task.update
            ('00000000-0000-0000-0000-000000000003'::uuid, '7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000003'::uuid, '9c8f7e61-5f3d-4b7f-bc65-0c6a7a9d8005'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            ('00000000-0000-0000-0000-000000000003'::uuid, '0e6d3a8b-0c8f-4a19-a2a9-8d6a3c8d7006'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid),
            -- viewer: board.view
            ('00000000-0000-0000-0000-000000000004'::uuid, '7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid, CURRENT_TIMESTAMP, '{system_user_id}'::uuid)
        ON CONFLICT (role_id, permission_id) DO NOTHING;
    """)

    op.execute("""
        UPDATE board_user_permissions
        SET role_id = '00000000-0000-0000-0000-000000000001'
        WHERE role_id IS NULL
    """)
    
    op.alter_column("board_user_permissions", "role_id", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM role_permissions
        WHERE (role_id, permission_id) IN (
            ('00000000-0000-0000-0000-000000000001'::uuid, '7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '1c4f1cdd-b4c5-41f4-b55d-2178356bd002'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, 'd7c47de2-2c1d-4c8a-8bc2-0f5c9d81a003'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '5b6e8f3a-2a6c-447e-9c60-7c15f50d4004'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '9c8f7e61-5f3d-4b7f-bc65-0c6a7a9d8005'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '0e6d3a8b-0c8f-4a19-a2a9-8d6a3c8d7006'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '2e3a9c8d-7d6b-4f3e-9b1c-5a6d7c8e9007'::uuid),
            ('00000000-0000-0000-0000-000000000001'::uuid, '4f7c6b2a-8d9e-4c1f-b0b7-6a8d5c2e1008'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '1c4f1cdd-b4c5-41f4-b55d-2178356bd002'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '5b6e8f3a-2a6c-447e-9c60-7c15f50d4004'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '9c8f7e61-5f3d-4b7f-bc65-0c6a7a9d8005'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '0e6d3a8b-0c8f-4a19-a2a9-8d6a3c8d7006'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '2e3a9c8d-7d6b-4f3e-9b1c-5a6d7c8e9007'::uuid),
            ('00000000-0000-0000-0000-000000000002'::uuid, '4f7c6b2a-8d9e-4c1f-b0b7-6a8d5c2e1008'::uuid),
            ('00000000-0000-0000-0000-000000000003'::uuid, '7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid),
            ('00000000-0000-0000-0000-000000000003'::uuid, '9c8f7e61-5f3d-4b7f-bc65-0c6a7a9d8005'::uuid),
            ('00000000-0000-0000-0000-000000000003'::uuid, '0e6d3a8b-0c8f-4a19-a2a9-8d6a3c8d7006'::uuid),
            ('00000000-0000-0000-0000-000000000004'::uuid, '7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid)
        );
        """
    )
    op.execute(
        """
        DELETE FROM roles WHERE id IN (
            '00000000-0000-0000-0000-000000000001'::uuid,
            '00000000-0000-0000-0000-000000000002'::uuid,
            '00000000-0000-0000-0000-000000000003'::uuid,
            '00000000-0000-0000-0000-000000000004'::uuid
        );
        """
    )
    op.execute(
        """
        DELETE FROM permissions WHERE id IN (
            '7a6f4c7a-1b5b-4f43-a9b8-2c3df7b4a001'::uuid,
            '1c4f1cdd-b4c5-41f4-b55d-2178356bd002'::uuid,
            'd7c47de2-2c1d-4c8a-8bc2-0f5c9d81a003'::uuid,
            '5b6e8f3a-2a6c-447e-9c60-7c15f50d4004'::uuid,
            '9c8f7e61-5f3d-4b7f-bc65-0c6a7a9d8005'::uuid,
            '0e6d3a8b-0c8f-4a19-a2a9-8d6a3c8d7006'::uuid,
            '2e3a9c8d-7d6b-4f3e-9b1c-5a6d7c8e9007'::uuid,
            '4f7c6b2a-8d9e-4c1f-b0b7-6a8d5c2e1008'::uuid
        );
        """
    )
    op.drop_constraint(None, 'board_user_permissions', type_='foreignkey')
    op.drop_column('board_user_permissions', 'role_id')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
