name: Deploy to Digital Ocean

on:
  workflow_call:
    secrets:
      DO_HOST:
        required: true
      DO_SSH_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          envs: IMAGE_TAG=${{ github.event.inputs.image_tag }}
          script: |
            cd todo-devops-lab

            echo "Updating local repository..."
            git pull origin test-deploy

            echo "Pull latest image from GHCR"
            docker compose -f docker-compose.yml pull

            echo "Restart containers with updated image"
            docker compose -f docker-compose.yml up -d
